Update rss.yml

diff --git a/.github/workflows/rss.yml b/.github/workflows/rss.yml
--- a/.github/workflows/rss.yml
+++ b/.github/workflows/rss.yml
@@ -43,11 +43,11 @@ jobs:
       - name: Esegui generazione feed (Tezze)
         run: python Tezze.py || echo "⚠️ Errore durante generazione Tezze, proseguo"
 
-      - name: Esegui generazione feed (Tezze)
+      - name: Esegui generazione feed (Velo)
         run: python Velo.py || echo "⚠️ Errore durante generazione Velo d'Astico, proseguo"
 
-      - name: Esegui generazione feed (Tezze)
-        run: python Velo.py || echo "⚠️ Errore durante generazione Velo d'Astico, proseguo"
+      - name: Esegui generazione feed (Torrebelvicino)
+        run: python Torrebelvicino.py || echo "⚠️ Errore durante generazione Torrebelvicino, proseguo"
       
       - name: Commit e push aggiornamenti
         run: |
