Update rss.yml

diff --git a/.github/workflows/rss.yml b/.github/workflows/rss.yml
--- a/.github/workflows/rss.yml
+++ b/.github/workflows/rss.yml
@@ -35,7 +35,7 @@ jobs:
         run: python Arzignano.py || echo "⚠️ Errore durante generazione Arzignano, proseguo"
 
       - name: Esegui generazione feed (Barbarano)
-        run: python Arzignano.py || echo "⚠️ Errore durante generazione Barbarano, proseguo"
+        run: python Barbarano.py || echo "⚠️ Errore durante generazione Barbarano, proseguo"
 
       - name: Commit e push aggiornamenti
         run: |
