Update rss.yml

diff --git a/.github/workflows/rss.yml b/.github/workflows/rss.yml
--- a/.github/workflows/rss.yml
+++ b/.github/workflows/rss.yml
@@ -30,11 +30,15 @@ jobs:
 
       - name: Esegui generazione feed (Malo)
         run: python Malo.py || echo "⚠️ Errore durante generazione Malo, proseguo"
+        
+      - name: Esegui generazione feed (Arzignano)
+        run: python Arzignano.py || echo "⚠️ Errore durante generazione Arzignano, proseguo"
 
       - name: Commit e push aggiornamenti
         run: |
           git config --global user.name "github-actions"
           git config --global user.email "github-actions@github.com"
+          git pull --rebase
           git add *.xml
           git commit -m "Aggiornamento automatico feed RSS" || echo "Nessuna modifica"
           git push
