Update rss.yml

diff --git a/.github/workflows/rss.yml b/.github/workflows/rss.yml
--- a/.github/workflows/rss.yml
+++ b/.github/workflows/rss.yml
@@ -37,8 +37,8 @@ jobs:
       - name: Esegui generazione feed (Barbarano)
         run: python Barbarano.py || echo "⚠️ Errore durante generazione Barbarano, proseguo"
 
-      - name: Esegui generazione feed (Barbarano)
-        run: python Barbarano.py || echo "⚠️ Errore durante generazione Barbarano, proseguo"
+      - name: Esegui generazione feed (Breganze)
+        run: python Breganze.py || echo "⚠️ Errore durante generazione Breganze, proseguo"
       
       - name: Commit e push aggiornamenti
         run: |
