Update rss.yml

diff --git a/.github/workflows/rss.yml b/.github/workflows/rss.yml
--- a/.github/workflows/rss.yml
+++ b/.github/workflows/rss.yml
@@ -42,6 +42,9 @@ jobs:
 
       - name: Esegui generazione feed (Tezze)
         run: python Tezze.py || echo "⚠️ Errore durante generazione Tezze, proseguo"
+
+      - name: Esegui generazione feed (Tezze)
+        run: python Velo.py || echo "⚠️ Errore durante generazione Velo d'Astico, proseguo"
       
       - name: Commit e push aggiornamenti
         run: |
